server:
  port: 8181
  path: /hello

#person:
#  lastName: zhangsan
#  age: 18
#  boss: false
#  birth: 2017/12/12
#  maps: {k1: v1,k2: v2}
#  lists:
#    - lisi
#    - zhangsan
#    - zhaoliu
#  dog:
#    name: xiaogao
#    age: 2